services:

  web:
    image: nginx:alpine
    container_name: nginx
    working_dir: /etc/nginx
    volumes:
      - ./app:/app
      - ./config/nginx:/etc/nginx/conf.d
      - ./app/log/nginx:/var/log/nginx/
    ports:
      - "80:80"
      - "443:443"
    restart: always
    depends_on:
      - php
      - db

  php:
    build:
      context: ./config/php
      dockerfile: Dockerfile
    container_name: php
    image: php:7.4
    working_dir: /app
    volumes:
      - ./app:/app
      - ./config/php7.4/php-ini-overrides.ini:/usr/local/etc/php/conf.d/00-php.ini
      - ./bin/sendmail:/usr/local/bin/sendmail
    restart: always
    environment:
      PHP_IDE_CONFIG: serverName=localhost

  db:
    container_name: postgres
    image: postgres:alpine
    environment:
      POSTGRES_DB: "dev"
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "root"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - ./config/postgresql/conf.d:/docker-entrypoint-initdb.d
      - ./app/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: always

  pgadmin:
    container_name: pgadmin
    image: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: "root@root.com"
      PGADMIN_DEFAULT_PASSWORD: "root"
    ports:
      - "5050:80"
    restart: always
